import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {once} from 'node:events';
import {probeOnce,identity} from '../lib/probe-transport.mjs';
const model='gpt-6-astra',routing={headers:{authorization:'Bearer local-unit-key',session_id:'local-session'},payload:{}};
async function call(t,handler,{signal,timeout=1}={}){const sockets=new Set(),server=http.createServer(async(req,res)=>{let raw='';for await(const part of req)raw+=part;assert.equal(JSON.parse(raw).input,'ping');assert.equal(JSON.parse(raw).model,model);assert.equal(JSON.parse(raw).max_output_tokens,16);assert.equal(req.headers['x-codex-turn-state'],undefined);await handler(req,res);});server.on('connection',s=>{sockets.add(s);s.on('close',()=>sockets.delete(s));});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>{for(const s of sockets)s.destroy();server.close();});return probeOnce(`http://127.0.0.1:${server.address().port}`,model,routing,'/responses',[292],signal,timeout);}
test('transport accepts same-model 292 with declared successful completion',async t=>{const r=await call(t,(_req,res)=>{res.writeHead(200,{'content-type':'application/json','x-codex-turn-state':'R'.repeat(292)});res.end(JSON.stringify({model,status:'completed'}));});assert.equal(r.accepted,true);assert.equal(r.state.length,292);assert.equal(r.responseModel,model);});
test('wrong-model 292 stays unaccepted; no fake model or token transformation',async t=>{const r=await call(t,(_req,res)=>{res.writeHead(200,{'content-type':'application/json','x-codex-turn-state':'R'.repeat(292)});res.end(JSON.stringify({model:'gpt-5.6-luna',status:'completed'}));});assert.equal(r.error,'model_mismatch');assert.equal(r.state,'');});
test('same-model 312 is a length miss and not a captured state',async t=>{const r=await call(t,(_req,res)=>{res.writeHead(200,{'content-type':'application/json','x-codex-turn-state':'R'.repeat(312)});res.end(JSON.stringify({model,status:'completed'}));});assert.equal(r.error,'length_miss');assert.equal(r.state,'');});
test('authentication errors, rate limits, redirects and server errors are surfaced',async t=>{for(const status of [401,403,429,302,500])await t.test(String(status),async st=>{const r=await call(st,(_req,res)=>{res.writeHead(status,{location:'http://127.0.0.1:1'});res.end();});assert.equal(r.error,'http_'+status);assert.equal(r.state,'');});});
test('a single connection timeout releases resources without declaring a hit',async t=>{const r=await call(t,()=>{},{timeout:.03});assert.equal(r.error,'timeout');assert.equal(r.accepted,false);});
test('missing response model is never guessed from requested model',async t=>{const r=await call(t,(_req,res)=>{res.writeHead(200,{'content-type':'application/json','x-codex-turn-state':'R'.repeat(292)});res.end('{"status":"completed"}');});assert.equal(r.error,'response_model_missing');});
test('failure events in HTTP 200 and conflicting response models do not qualify',async t=>{const r=await call(t,(_req,res)=>{res.writeHead(200,{'content-type':'text/event-stream','x-codex-turn-state':'R'.repeat(292)});res.end('data: '+JSON.stringify({type:'response.created',response:{model}})+'\n\n'+'data: '+JSON.stringify({type:'response.failed',response:{model,status:'failed'}})+'\n\n');});assert.equal(r.error,'response_failed');assert.equal(r.state,'');});
test('output-limit completion qualifies without pretending all output completed',async t=>{const r=await call(t,(_req,res)=>{res.writeHead(200,{'content-type':'text/event-stream','x-codex-turn-state':'R'.repeat(292)});res.end('data: '+JSON.stringify({type:'response.incomplete',response:{model,status:'incomplete',incomplete_details:{reason:'max_output_tokens'}}})+'\n\n');});assert.equal(r.accepted,true);assert.equal(r.completed,false);});
test('routing identity excludes prompts, cookies, old state and arbitrary headers',()=>{const r=identity({authorization:'Bearer test',session_id:'s',cookie:'private','x-codex-turn-state':'old','x-extra':'unknown'},{prompt_cache_key:'key',metadata:{turn_id:'t',private:'secret'},input:'private'});assert.deepEqual(Object.keys(r.headers).sort(),['authorization','session_id']);assert.equal(JSON.stringify(r).includes('private'),false);});
